name: Build & Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - uses: olafurpg/setup-scala@v13
        id: setup-scala
        with:
          java-version: '1.8'
      - run: sbt scalastyle
      - run: yarn install
      - run: yarn coffeelint
      - run: sbt test
